### ISSUE TITLE
Won't build on any Ubuntu newer than 21.04 

### ISSUE THREAD

**Issue by ptrxyz** [CamAnNguyen/rdkit_chem#7]
Sadly this does not work on Ubuntu 21.10 on wards. I assume it's because Ubuntu 21.10 (impish) installed libc6 (glibc) 2.34, which introduced a major ABI change. SIGSTKSZ is now no longer constant, and can’t be used directly to define array sizes.

I used Ubuntu 21.10, Boost libraries 1.74 and GCC9.

<details> 
<summary>some excrept from the logs:</summary>

```
Consolidate compiler generated dependencies of target ChemicalFeatures_static
Consolidate compiler generated dependencies of target testChemicalFeatures
[ 29%] Built target testChemicalFeatures
[ 29%] Built target ChemicalFeatures_static
[ 29%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/AdjustQuery.cpp.o
[ 29%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol_static.dir/AdjustQuery.cpp.o
In file included from /usr/include/signal.h:328,
                 from /cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/External/catch/catch/single_include/catch.hpp:4716,
                 from /cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/Code/SimDivPickers/catch_tests.cpp:13:
/cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/External/catch/catch/single_include/catch.hpp:7320:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 7320 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                             ^~~~~~~~
In file included from /usr/include/signal.h:328,
                 from /cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/External/catch/catch/single_include/catch.hpp:4716,
                 from /cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/Code/Geometry/catch_tests.cpp:3:
/cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/External/catch/catch/single_include/catch.hpp:7320:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 7320 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                             ^~~~~~~~
In file included from /usr/include/signal.h:328,
                 from /cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/External/catch/catch/single_include/catch.hpp:4716,
                 from /cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/Code/Numerics/testConrec.cpp:12:
/cache/bundle/ruby/2.6.0/bundler/gems/rdkit_chem-f96b802a7f22/rdkit/External/catch/catch/single_include/catch.hpp:7320:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 7320 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                             ^~~~~~~~
make[2]: *** [Code/SimDivPickers/CMakeFiles/pickersTestsCatch.dir/build.make:76: Code/SimDivPickers/CMakeFiles/pickersTestsCatch.dir/catch_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:10860: Code/SimDivPickers/CMakeFiles/pickersTestsCatch.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [Code/Numerics/CMakeFiles/testConrec.dir/build.make:76: Code/Numerics/CMakeFiles/testConrec.dir/testConrec.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3386: Code/Numerics/CMakeFiles/testConrec.dir/all] Error 2
make[2]: *** [Code/Geometry/CMakeFiles/geometryTestsCatch.dir/build.make:76: Code/Geometry/CMakeFiles/geometryTestsCatch.dir/catch_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3330: Code/Geometry/CMakeFiles/geometryTestsCatch.dir/all] Error 2
[ 29%] Linking CXX shared library ../../lib/libRDKitcoordgen.so
[ 29%] Built target coordgen
[ 29%] Linking CXX static library libRDKitcoordgen_static.a
[ 29%] Built target coordgen_static
[ 29%] Linking CXX shared library ../../lib/libRDKitGraphMol.so
[ 29%] Linking CXX static library libRDKitGraphMol_static.a
[ 32%] Built target GraphMol_static
[ 35%] Built target GraphMol
make: *** [Makefile:166: all] Error 2
```
</details>

**Comment by ptrxyz** [comment]
For reference, one thing I tried was to simply disable testing since it seems the problem is related to catch. No success though. :/

**Comment by ptrxyz** [comment]
Still present as of today. Can we prioritize this as it's needed for the docker builds to work.

**Comment by ptrxyz** [comment]
I'm bumping this up. Can you please take care of it? Would be a pity to fork this, just cause it's lingering around forever.

**Comment by CamAnNguyen** [comment]
@ptrxyz Sorry for late reply. I've fixed the gem to work with Ubuntu 22.04 onwards and Ruby 3.2+
